version: '3'
services:
  bedrock:
    image: minecraft-bedrock-playit-gg
    command: /opt/bedrock/bedrock_server
  playit:
    image: minecraft-bedrock-playit-gg
    command: playit
    network_mode: service:bedrock
    volumes:
      - ./etc/playit:/etc/playit
